name       : gptfdisk
version    : 1.0.4
release    : 4
source     :
    - https://sourceforge.net/projects/gptfdisk/files/gptfdisk/1.0.4/gptfdisk-1.0.4.tar.gz/download : b663391a6876f19a3cd901d862423a16e2b5ceaa2f4a3b9bb681e64b9c7ba78d
license    : GPL-2.0
component  : system.utils
summary    : GPT fdisk-like utility
description: |
    GPT fdisk is a disk partitioning tool loosely modeled on Linux fdisk, but used for modifying GUID Partition Table (GPT) disks. The related FixParts utility fixes some common problems on Master Boot Record (MBR) disks.
builddeps  :
    - pkgconfig(popt)
build      : |
    %make
install    : |
    for i in cgdisk sgdisk gdisk fixparts ; do
        install -D -m 00755 ${i} $installdir/usr/sbin/${i}
        install -D -m 00644 ${i}.8 $installdir/usr/share/man/man8/${i}.8
    done
